### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by yamasy1549** [eliz40x/eliz40x.github.io#1]
hey, @eliz40x. This is a nice page!

But unfortunately I found an error:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

I checked your sources, and there are invalid code.
```html
<script src="./css/jquery.js"></script>
<script src="./css/selectfile.js"></script>
```

`./css/jquery.js` and `./css/selectfile.js` are not exist. I guess it's your mistake, isn't it?

**Comment by eliz40x** [comment]
I mistook, no page`./css/jquery.js` and `./css/selectfile.js` used
I forget edit default template

**Comment by yamasy1549** [comment]
![寿司ゆき:happy](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/24.png)
